
name: Website Deployment

on:
  push:
    branches:
      - tmp
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 👇 Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install -g pnpm
      - run: pnpm install
      - name: Build
        run: pnpm run build
      - name: deploy files
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - run: mkdir -p ~/.ssh
      - run: echo '43.153.36.204 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFsRPdRZaT1gNZDjrt4XHov5c/1Raz4wduIo3dfjeEAt' >> ~/.ssh/known_hosts
      - run: echo '43.153.36.204 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwpU3KS710EYvqG6CYoYKQKBhZ6VOg2QxJSL7nlXgeMzS9SktspyT/EQ+HFRU5g9StbvCOpNUBgONclMlIoPlt7hDFtt09mNCGKUnnqa8W07K/1nmeojeHTX3z1Bb5W+Pj5gOsSupt/3zSGU5Ki7hk17fb3KADHf7Mw8EEQCdD1aTXeyb3Ov65rs0V4jJdJLwUZzpJwO1pBYJ03RJX+wXMsaMkZiaNmeBQ8Jvsmtc+nN+ymVf5tNJkUl0fGTz43GPM6+UL/4mLEJog2w3l8EdkhinkRI6ipqhgs5A30kUZUybh0DUAElANvqwWPrE2K6x9x5ZLKKP0e54CRx/2ahjUUDu0vQVSwCN1oftuXhvRM7iiLjxdOofJiyhB5Xe9IK8Vl5/FViZcbI41embQG3mcf3a1AbY9kdcATUnZ2K7gR7nX9gaKEGVL7XLCqwRHR3erIa/fp5cHi7bpWlw7+kymD0cm/6NODPBM3DNO7m8l8A8pty1QHcqBnsj7/iGLO7k=' >> ~/.ssh/known_hosts
      - run: echo '43.153.36.204 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEO9ZXlRWOyxPpPB+CvhGxPpHEsdXUNM2BiOt2n3cvas44CE7aaHjkJZzcZ2/U9ql8EIY5kJEXky5pPCoJtM2m4=' >> ~/.ssh/known_hosts
      - name: Upload files to the online
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            sftp admin@wuchuheng.com <<EOF
                cd /home/admin/web/wuchuheng.com/public_html
                lcd build
                put -r * ./

      - name: Install json5
        run: npm install -g json5
      - run: json5 ./config.json5
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "::set-output name=config::$(json5 ./config.json5 | jq -r tostring)"
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
