# deploy.yml
name: deploy blog to  server
on:
  push:
    branches:
      - deploy-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 使用 node
      - name: use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      # npm install
      - name: npm install
        run: |
          npm install -g yarn
          yarn
        env:
          CI: true
      # build
      - name: doc build
        run: |
          node -v
          ls -ahl
          yarn build
        env:
          CI: true

#       # Deploy
#       - name: Deploy
#         uses: easingthemes/ssh-deploy@v2.0.7
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
#           ARGS: "-avz --delete"
#           SOURCE: "public/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.TARGET }}
